#!/bin/bash

#######

label () {
    printf " \b----------\n$1\n----------\n"
}

CC () {
    gcc -g -Wall -Wextra $@
}

######## Tests

echo ""

label "test.h" && CC ./test_test.c && ./a.out
label "benchmark.h" && CC ./test_benchmark.c && ./a.out
label "bits.h" && CC ./test_bits.c && ./a.out

echo ""

########
